name: music_player
description: A new Flutter project.

publish_to: 'none' # This ensures the project is not published to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  cupertino_icons: ^1.0.2
  audioplayers: ^6.1.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  #assets:






  # To add other images, include them like below:
  # assets:
  #   - assets/a_dot_burr.jpeg
  #   - assets/a_dot_ham.jpeg
